"""auto-vote

Revision ID: 89e6ff3b045a
Revises: ad7e8a0ec2b7
Create Date: 2022-06-25 12:26:56.669309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89e6ff3b045a"
down_revision = "ad7e8a0ec2b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vote",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vote")
    # ### end Alembic commands ###
